### ISSUE TITLE
Merge cells does not work properly if there are several sheets in the template file

### ISSUE THREAD

**Issue by vkuzmenok** [davidsclarke/Excel-Template-XLSX#1]
There is an issue with the resulting Excel file with the "merged" cells. The problem occurs, when the template file has several sheets, and on the sheets there are merged cells with different merge range.
E.g. Sheet1 has cell C2 with merge range C2:F2 and Sheet2 has cell C2 with merge range C2:L6
Because Sheet2 is parsed second, parse sub overrides internal MERGED_RANGES structure with the new range. Because of this, resulting Excel file will have merged cell C2 with the range C2:L6 on sheets Sheet1 and Sheet2

**Comment by vkuzmenok** [comment]
For the time being, I changed the source code on my server by adding one additional level to the MERGED_RANGES structure.
Below are proposed changes:

In the Merged cells sub of _parse_sheet_pass1

$self->{MERGED_RANGES}{$sheet->{_index}}{$topleft} = $ref;

In the sheetData/row sub of _parse_sheet_pass2

         my $sheet_idx = $sheet->{_index};
         for my $cell ( $row_elt->children('c') ) {
 .....
               if ( my $ref = $self->{MERGED_RANGES}{$sheet_idx}{$a1} ) {

**Comment by davidsclarke** [comment]
Posted version 1.0.8, which incorporates the proposed changes.  Included a test script to verify.
